# Generated by Django 5.2.8 on 2025-11-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twobeats_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': '태그', 'verbose_name_plural': '태그'},
        ),
        migrations.AlterField(
            model_name='music',
            name='music_type',
            field=models.CharField(choices=[('ballad', '발라드'), ('dance', '댄스'), ('hiphop', '힙합'), ('rnb', 'R&B'), ('rock', '록'), ('pop', '팝'), ('indie', '인디'), ('trot', '트로트'), ('jazz', '재즈'), ('ost', 'OST'), ('etc', '기타')], max_length=20, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='music',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='musics', to='twobeats_upload.tag', verbose_name='태그'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='videos', to='twobeats_upload.tag', verbose_name='태그'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[('mv', '뮤직비디오'), ('performance', '퍼포먼스'), ('live', '라이브'), ('cover', '커버'), ('dance', '댄스 영상'), ('documentary', '다큐멘터리'), ('behind', '비하인드'), ('etc', '기타')], max_length=20, verbose_name='장르'),
        ),
    ]
