# Generated by Django 5.2.8 on 2025-11-25 14:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True, db_column='historylist_played_at', verbose_name='재생일시')),
            ],
            options={
                'verbose_name': '재생 이력',
                'verbose_name_plural': '재생 이력',
                'db_table': 'historylist',
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(db_column='playlist_folder_name', max_length=100, verbose_name='폴더명')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='playlist_created_at', verbose_name='생성일')),
            ],
            options={
                'verbose_name': '플레이리스트',
                'verbose_name_plural': '플레이리스트',
                'db_table': 'playlist',
            },
        ),
        migrations.CreateModel(
            name='PlaylistMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(db_column='pm_order', default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='pm_created_at', verbose_name='추가일')),
            ],
            options={
                'verbose_name': '플레이리스트 음악',
                'verbose_name_plural': '플레이리스트 음악',
                'db_table': 'playlist_music',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(db_column='pv_order', default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='pv_created_at', verbose_name='추가일')),
            ],
            options={
                'verbose_name': '플레이리스트 영상',
                'verbose_name_plural': '플레이리스트 영상',
                'db_table': 'playlist_video',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='고유ID')),
                ('phone_number', models.CharField(blank=True, db_column='user_pnum', max_length=20, verbose_name='전화번호')),
                ('profile_image', models.ImageField(blank=True, db_column='user_image', null=True, upload_to='profiles/', verbose_name='프로필 이미지')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
