# Generated by Django 5.2.8 on 2025-11-25 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twobeats_account', '0001_initial'),
        ('twobeats_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historylist',
            name='music',
            field=models.ForeignKey(db_column='historylist_music_id', on_delete=django.db.models.deletion.CASCADE, to='twobeats_upload.music', verbose_name='음악'),
        ),
        migrations.AddField(
            model_name='historylist',
            name='user',
            field=models.ForeignKey(db_column='historylist_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(db_column='playlist_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='playlistmusic',
            name='music',
            field=models.ForeignKey(db_column='pm_music_id', on_delete=django.db.models.deletion.CASCADE, to='twobeats_upload.music', verbose_name='음악'),
        ),
        migrations.AddField(
            model_name='playlistmusic',
            name='playlist',
            field=models.ForeignKey(db_column='pm_playlist_id', on_delete=django.db.models.deletion.CASCADE, related_name='playlist_musics', to='twobeats_account.playlist', verbose_name='플레이리스트'),
        ),
        migrations.AddField(
            model_name='playlistvideo',
            name='playlist',
            field=models.ForeignKey(db_column='pv_playlist_id', on_delete=django.db.models.deletion.CASCADE, related_name='playlist_videos', to='twobeats_account.playlist', verbose_name='플레이리스트'),
        ),
        migrations.AddField(
            model_name='playlistvideo',
            name='video',
            field=models.ForeignKey(db_column='pv_video_id', on_delete=django.db.models.deletion.CASCADE, to='twobeats_upload.video', verbose_name='영상'),
        ),
        migrations.AlterUniqueTogether(
            name='playlistmusic',
            unique_together={('playlist', 'music')},
        ),
        migrations.AlterUniqueTogether(
            name='playlistvideo',
            unique_together={('playlist', 'video')},
        ),
    ]
