# Generated by Django 5.2.8 on 2025-11-25 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twobeats_upload', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(db_column='mc_content', verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='mc_created_at', verbose_name='작성일')),
                ('music', models.ForeignKey(db_column='mc_music_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='twobeats_upload.music', verbose_name='음악')),
                ('user', models.ForeignKey(db_column='mc_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '음악 댓글',
                'verbose_name_plural': '음악 댓글',
                'db_table': 'music_comment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MusicLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='ml_created_at', verbose_name='좋아요일')),
                ('music', models.ForeignKey(db_column='ml_music_id', on_delete=django.db.models.deletion.CASCADE, to='twobeats_upload.music', verbose_name='음악')),
                ('user', models.ForeignKey(db_column='ml_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '음악 좋아요',
                'verbose_name_plural': '음악 좋아요',
                'db_table': 'music_like',
                'unique_together': {('user', 'music')},
            },
        ),
    ]
