# Generated by Django 5.2.8 on 2025-11-25 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='tag_name', max_length=50, unique=True, verbose_name='태그명')),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그',
                'db_table': 'tag_table',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_title', models.CharField(max_length=200, verbose_name='제목')),
                ('music_singer', models.CharField(max_length=100, verbose_name='가수')),
                ('music_type', models.CharField(max_length=50, verbose_name='장르')),
                ('music_root', models.FileField(upload_to='music/', verbose_name='음원파일')),
                ('music_thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/music/', verbose_name='썸네일')),
                ('music_count', models.IntegerField(default=0, verbose_name='재생수')),
                ('music_like_count', models.IntegerField(default=0, verbose_name='좋아요수')),
                ('music_created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('music_updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('uploader', models.ForeignKey(db_column='music_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_musics', to=settings.AUTH_USER_MODEL, verbose_name='업로더')),
                ('tags', models.ManyToManyField(blank=True, related_name='musics', to='twobeats_upload.tag')),
            ],
            options={
                'verbose_name': '음악',
                'verbose_name_plural': '음악',
                'db_table': 'music',
                'ordering': ['-music_created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=200, verbose_name='제목')),
                ('video_singer', models.CharField(max_length=100, verbose_name='아티스트')),
                ('video_type', models.CharField(max_length=50, verbose_name='장르')),
                ('video_root', models.FileField(upload_to='videos/', verbose_name='영상파일')),
                ('video_detail', models.TextField(blank=True, verbose_name='상세설명')),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/video/', verbose_name='썸네일')),
                ('video_time', models.IntegerField(default=0, verbose_name='재생시간(초)')),
                ('video_views', models.IntegerField(default=0, verbose_name='조회수')),
                ('video_play_count', models.IntegerField(default=0, verbose_name='재생수')),
                ('video_created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('video_updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('tags', models.ManyToManyField(blank=True, related_name='videos', to='twobeats_upload.tag')),
                ('video_user', models.ForeignKey(db_column='video_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL, verbose_name='업로더')),
            ],
            options={
                'verbose_name': '영상',
                'verbose_name_plural': '영상',
                'db_table': 'video',
                'ordering': ['-video_created_at'],
            },
        ),
    ]
