# Generated by Django 5.2.8 on 2025-11-26 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twobeats_upload', '0002_alter_tag_options_alter_music_music_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldCupGame',
            fields=[
                ('wc_game_serial_key', models.BigAutoField(db_column='wc_game_serial_key', primary_key=True, serialize=False, verbose_name='게임 고유키')),
                ('wc_total_rounds', models.IntegerField(default=16, help_text='예: 16강, 32강', verbose_name='총 라운드')),
                ('wc_created_at', models.DateTimeField(auto_now_add=True, db_column='wc_created_at', verbose_name='게임 일시')),
                ('wc_user', models.ForeignKey(blank=True, db_column='wc_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='world_cup_games', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '월드컵 게임',
                'verbose_name_plural': '월드컵 게임',
                'db_table': 'world_cup_game',
                'ordering': ['-wc_created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorldCupResult',
            fields=[
                ('wc_result_serial_key', models.BigAutoField(db_column='wc_result_serial_key', primary_key=True, serialize=False, verbose_name='결과 고유키')),
                ('wc_final_rank', models.IntegerField(help_text='1(우승), 2(준우승), 4(4강)...', verbose_name='최종 등수')),
                ('wc_score', models.IntegerField(default=0, help_text='랭킹 산정을 위한 가중치 점수 (예: 우승=50점)', verbose_name='랭킹 점수')),
                ('wc_game', models.ForeignKey(db_column='wc_game_id', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='twobeats_worldcup.worldcupgame', verbose_name='게임')),
                ('wc_music', models.ForeignKey(db_column='wc_music_id', on_delete=django.db.models.deletion.CASCADE, to='twobeats_upload.music', verbose_name='음악')),
            ],
            options={
                'verbose_name': '월드컵 상세결과',
                'verbose_name_plural': '월드컵 상세결과',
                'db_table': 'world_cup_result',
                'indexes': [models.Index(fields=['wc_game'], name='world_cup_r_wc_game_0b8e8b_idx'), models.Index(fields=['wc_music'], name='world_cup_r_wc_musi_dae624_idx')],
            },
        ),
    ]
