# Generated by Django 5.2.8 on 2025-12-02 00:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twobeats_upload', '0002_alter_tag_options_alter_music_music_type_and_more'),
        ('twobeats_worldcup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomWorldCup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='월드컵 제목')),
                ('access_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('musics', models.ManyToManyField(related_name='included_custom_wcs', to='twobeats_upload.music', verbose_name='후보곡 목록')),
            ],
        ),
        migrations.AddField(
            model_name='worldcupgame',
            name='custom_worldcup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='played_games', to='twobeats_worldcup.customworldcup'),
        ),
    ]
