# Generated by Django 5.2.8 on 2025-11-25 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twobeats_upload', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldCupResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='world_cup_created_at', verbose_name='플레이일시')),
                ('user', models.ForeignKey(db_column='world_cup_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('winner_music', models.ForeignKey(db_column='world_cup_music', on_delete=django.db.models.deletion.CASCADE, to='twobeats_upload.music', verbose_name='우승곡')),
            ],
            options={
                'verbose_name': '월드컵 결과',
                'verbose_name_plural': '월드컵 결과',
                'db_table': 'world_cup',
            },
        ),
    ]
